---
title: "linear_models"
author: "Chhiring Lama"
date: "2024-11-07"
output: github_document
---

```{r setup, include=FALSE, message = FALSE}
library(tidyverse)
library(p8105.datasets)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "85%", 
	fig.align = "center"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

set.seed(1)
```

Import the dataset and do some data cleaning:
```{r}
data("nyc_airbnb")

nyc_airbnb <-  
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  rename(borough = neighbourhood_group,
    neighborhood = neighbourhood) |> 
  filter(borough != "Staten Island") |> 
  select(price, stars, borough, neighborhood, room_type) |> 
  mutate(borough = fct_infreq(borough), 
         room_type = fct_infreq(room_type))
    
```

Fit linear regression to predict price using stars and borough

Relatively simple:
```{r}
fit <- lm(price ~ stars + borough, data = nyc_airbnb)

summary(fit)

names(summary(fit))

coef(fit)

fit |> 
  broom::tidy() |> 
  select(term, estimate, `p.value`)

fit |> 
  broom::glance()
```

Try a more complex model
```{r}
fit <- lm(price ~ stars + borough, data = nyc_airbnb)

fit |> 
  broom::tidy() |> 
  select(term, estimate, `p.value`) |> 
  mutate(term = str_replace(term, "borough", "Borough:")) |> 
  knitr::kable(digits = 3)
```

## Some diagnostics

(backtrack to some EDA)

```{r}
nyc_airbnb |> 
  ggplot(aes(y = price, x = stars)) +
  geom_point() +
  stat_smooth(method = "lm")
```


Most diagnostics use residuals
```{r}
modelr::add_residuals(nyc_airbnb, fit) |> 
  ggplot(aes(x = resid)) +
  geom_histogram()
```

```{r}
modelr::add_residuals(nyc_airbnb, fit) |> 
  ggplot(aes(x = borough, y = resid)) +
  geom_violin() +
  ylim(-200, 500)
```

Residuals against stars
```{r}
modelr::add_residuals(nyc_airbnb, fit) |> 
  ggplot(aes(x = stars, y = resid)) +
  geom_point()
```

Residuals against fitted values
```{r}
nyc_airbnb |> 
  modelr::add_residuals(fit) |> 
  modelr::add_predictions(fit) |> 
  ggplot(aes(x = pred, y = resid)) +
  geom_point()
```





